### ISSUE TITLE
Some small changes

### ISSUE THREAD

**Issue by anoomolu** [KonSola5/BotaniaConfigurator#1]
Hiya! Thank you so much for making this, I've been looking for a Botania tweaking mod for ages now, it's gonna be so helpful to balance my pack.

Two small things I wanted to mention:
- There's a spelling error in the config (petitie instead of petite)
- Would it be possible to add a config for the input block for the Clayconia? Imo making it turn mud into clay might fit vanilla better, skipping the boring process of waiting for dripstone drying.

**Comment by KonSola5** [comment]
1. Already noticed that, will correct.
2. It's 100% possible.

**Comment by KonSola5** [comment]
An update 1.1.1 has been pushed to CF and Modrinth that adds the ability to change blocks that Clayconia converts into Clay.

Tag your block `#botaniaconfigurator:clayconia_convertable` to make that block convertable by Clayconia.

You can also disable the standard Sand conversion in the config.
