### ISSUE TITLE
Changing Mana Pool capacity doesn't affect mana pool cart capacity

### ISSUE THREAD

**Issue by anoomolu** [KonSola5/BotaniaConfigurator#2]
Heya, been having a blast with buffing the kekimurus, adjusting the orechid ignem to make more sense in my pack and overall just making the mod feel a bit more like I've always wanted it to play out.

** Describe the bug**
I adjusted the capacity of the normal mana pool to 10,000, but when testing the Minecart with Mana Pool, the total amount stored didn't appear to change from default (1,000,000). Can be tested by pumping mana from a Creative pool to the pool minecart, breaking the pool and pumping the mana from the cart to a normal pool. Ideally all the mana would be transferred, but it seems like the mana cart's mana barely goes down.

** Versions **
- Botania Configurator: 1.1.1+1.20.1
- Botania: 1.20.1-441-FABRIC

~~I guess a wider suggestion would be to add a config for the mana tablet and greater band of mana to match the configurability of mana pools, but I didn't want to spam the issue tracker 😭~~

**Comment by KonSola5** [comment]
The config option should affect **newly** placed pools, since the info about the capacity is added to NBT upon placing the pool.
